### ISSUE TITLE
CGAL point issue

### ISSUE THREAD

**Issue by Taochen12138** [STORM-IRIT/Plane-Detection-Point-Cloud#13]
![企业微信截图_16397206571212](https://user-images.githubusercontent.com/46017788/146496566-4f14b7fc-1ae3-4d8d-93bc-334b751dd296.png)
as you can see, how the bug should be removed?

**Comment by Taochen12138** [comment]
Oh, I have found what is wrong. The version of CGAL is 4.11 while the project tests on 5.02

**Comment by tojiboyevf** [comment]
> Oh, I have found what is wrong. The version of CGAL is 4.11 while the project tests on 5.02

Hi! How did you install 5.02 version of CGAL? Could you share the instruction for installing 5.02 version, please? I have some trouble with installing the latest version of CGAL. Thanks in advance!
