### ISSUE TITLE
How did you estimate normals of point clouds which don't have an oriented normal vector of each input point?

### ISSUE THREAD

**Issue by tojiboyevf** [STORM-IRIT/Plane-Detection-Point-Cloud#14]
Dear Sir,

Thanks for your effort and work! I wanted to use your repository but my pointcloud doesn't have an oriented normal vector of each input point. There are many approaches to estimate normal but all of them give different results. May I know what script did you use in order to find an oriented normal vector of each input point?
Thanks for your attention!

Yours faithfully,
Fakhriddin Tojiboev

**Comment by nmellado** [comment]
Dear @tojiboyevf,
In our experiment we used the normal estimation filter in Meshlab, using default parameters.
Our approach can work even if some samples have locally inverted normals, even if it is not ideal.
What kind of objects are represented by your point clouds ?

**Comment by tojiboyevf** [comment]
@nmellado Thanks for your response! I will try your method too!
I am using ICM-NUIM dataset https://www.doc.ic.ac.uk/~ahanda/VaFRIC/iclnuim.html
