### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by yidahuang** [STORM-IRIT/Plane-Detection-Point-Cloud#15]
Hi, thanks for your good work. I would like to test it on LiDAR point clouds. It runs successfully in my ubuntu-desktop. However, I have a problem with compiling the program MacOSX 12.2 with Apple M1 chip.   Is the provided PDPC library compatible with Apple M1 chip?

## Issue Details
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /Users/huangjin/Documents/Research/lib/Plane-Detection-Point-Cloud/cmake-build-debug --target pdpcComputeMultiScaleFeatures
[1/54] Building CXX object CMakeFiles/pdpclib.dir/src/PDPC/Persistence/Component.cpp.o
FAILED: CMakeFiles/pdpclib.dir/src/PDPC/Persistence/Component.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++  -I/Users/huangjin/Documents/Research/lib/Plane-Detection-Point-Cloud/src -Wall -Wextra -DPDPC_DEBUG -g3 -ggdb -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -std=gnu++14 -MD -MT CMakeFiles/pdpclib.dir/src/PDPC/Persistence/Component.cpp.o -MF CMakeFiles/pdpclib.dir/src/PDPC/Persistence/Component.cpp.o.d -o CMakeFiles/pdpclib.dir/src/PDPC/Persistence/Component.cpp.o -c /Users/huangjin/Documents/Research/lib/Plane-Detection-Point-Cloud/src/PDPC/Persistence/Component.cpp
/Users/huangjin/Documents/Research/lib/Plane-Detection-Point-Cloud/src/PDPC/Persistence/Component.cpp:30:9: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
        PDPC_DEBUG_ASSERT(false);

**Comment by yidahuang** [comment]
Hi @nmellado,

Thanks for your help, I tried another branch, it works now. Btw, I want to use your software in my research, any idea to provide a simple IO function for this library so I can easily use it?

**Comment by nmellado** [comment]
I have merged the fix in `master`.
Let's discuss the IO issue in a dedicated thread.
