### ISSUE TITLE
IO functions

### ISSUE THREAD

**Issue by nmellado** [STORM-IRIT/Plane-Detection-Point-Cloud#17]
Hi @nmellado,

Thanks for your help, I tried another branch, it works now. Btw, I want to use your software in my research, any idea to provide a simple IO function for this library so I can easily use it?

_Originally posted by @yidahuang in https://github.com/STORM-IRIT/Plane-Detection-Point-Cloud/issues/15#issuecomment-1036182654_

**Comment by nmellado** [comment]
File loading and saving is provided by the `Loader` class:
https://github.com/STORM-IRIT/Plane-Detection-Point-Cloud/blob/7d0b489502d2bf3c3e7b21ab956ec48cb63c5022/src/PDPC/PointCloud/Loader.h#L9-L15

Example of usage:
* Load: https://github.com/STORM-IRIT/Plane-Detection-Point-Cloud/blob/7d0b489502d2bf3c3e7b21ab956ec48cb63c5022/app/pdpcSegmentation.cpp#L71-L73
* Save: https://github.com/STORM-IRIT/Plane-Detection-Point-Cloud/blob/7d0b489502d2bf3c3e7b21ab956ec48cb63c5022/app/pdpcSegmentation.cpp#L188

**Comment by yidahuang** [comment]
Many thanks. This is exactly what I want (:
